format = """
$username$hostname$directory$env_var$git_branch$git_commit$git_state$cmd_duration$line_break\
$character"""

[username]
format      = "[$user]($style)"
show_always = true

[hostname]
format    = "@[$hostname]($style)"
ssh_only  = false

[directory]
format            = ":[$path]($style)[$readonly]($readonly) "
truncation_length = 0
truncate_to_repo  = false

[character]
success_symbol  = "[\U0001F604❯](bold green)"
error_symbol    = "[\U0001F62D❯](bold red)"

[env_var.VIFM]
format  = "in [VIFM]($style) "
style   = "bold blue"

[env_var.NVIM]
format  = "in [NVIM]($style) "
style   = "bold green"

[env_var.TMUX]
format  = "in [TMUX]($style) "
style   = "bold green"
